carro/urls.py
from django.urls import path
from . import views


app_name="carro"

urlpatterns = [

    path('',views.carrito,name="Carro"),
    path("agregar/<int:producto_id>/",views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/",views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/",views.restar_producto, name="restar"),
    path("limpiar/",views.limpiar_carro, name="limpiar"),
    path("actualizar/<int:producto_id>/<int:cantidad>/",views.actualizar_carro, name="actualizar"),


]

peluqueriamim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('peluqueriamimapp.urls')),

    path('productos/', include('producto.urls')),

    path('contacto/', include('contacto.urls')),

    path('autenticacion/', include('autenticacion.urls')),

    path('pedidos/', include('pedidos.urls')),

    path('carro/', include('carro.urls')),



]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/models.py
from django.db import models

# Create your models here.

carro/views.py
from django.shortcuts import render, redirect

from .carro import Carro

from producto.models import Producto


# Create your views here.


def carrito(request):
    return render(request, "carro/carrito.html")

def agregar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("Productos")


def eliminar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("Productos")

def restar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.restar_producto(producto=producto)

    return redirect("Productos")

def limpiar_carro(request):

    carro=Carro(request)

    carro.limpiar_carro()

    return redirect("Productos")

def actualizar_carro(request, producto_id, cantidad):
    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.actualizar_carro(producto=producto, cantidad=cantidad)

    return redirect("carro:Carro")

    

carro/templates/carro/carrito.html
{% extends "peluqueriamimapp/base.html" %}

{% load static %}
{% block content %}

{% if request.user.is_authenticated %}
<br/>
<div class="container">
    <div style="float: right;">
    <table class="table table-bordered" id="finalizar_compra" style="color: white;">
        <thead>
            <tr>
                <td colspan="2">total : {{importe_total_carro}}</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="2"><a class="btn btn-success" href="{% url 'procesar_pedido' %}">Finalizar compra</a></td>
            </tr>

        </tbody>
    </table>
</div>
</div>



<div class="container">
    <table class="table" id="carrito_compras" style="color: white;">
        <thead>
            <tr>
                <td><h4>Tus productos</h4></td>
                <td>Precio</td>
                <td>Cantidad</td>
                <td>Subtotal</td>
            </tr>
        </thead>
        <tbody>
            {%if request.session.carro.items %}
            {%for key, value in request.session.carro.items%}
                <tr>
                    <td>
                        <img src="{{value.imagen}}" width="200px" height="200px">
                            <h5><strong>{{value.nombre}}</strong></h5>
                    </td>
                    <td>{{value.costo}}</td>
                    <td>
                        
                            <a class="btn btn-primary dropdown-toggle" id="navbarDropdown1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <h5>{{value.cantidad}}</h5></a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                            <a class="dropdown-item tex-center" href="{% url 'carro:actualizar' value.producto_id  1 %}">1</a>
                            <a class="dropdown-item tex-center" href="{% url 'carro:actualizar' value.producto_id  2 %}">2</a>
                            <a class="dropdown-item tex-center" href="{% url 'carro:actualizar' value.producto_id  3 %}">3</a>
                            <a class="dropdown-item tex-center" href="{% url 'carro:actualizar' value.producto_id  4 %}">4</a>
                            <a class="dropdown-item tex-center" href="{% url 'carro:actualizar' value.producto_id  5 %}">5</a>
                            <a class="dropdown-item tex-center" href="{% url 'carro:actualizar' value.producto_id  6 %}">6</a>
                            
                        </div>

                    </td>
                    <td>
                        $ {{value.precio}}
                    </td>
                    
                </tr>               
            {% endfor %}
            {% endif %}


        </tbody>
    </table>
</div>

{% else %}
<br/>
<div class="alert alert-success container" role="alert">
  <h4 class="alert-heading"><strong>Inicia Sesion</strong></h4>
  <p>Debes iniciar sesion para poder agregar productos al carro</p>
  <hr>
  <p class="mb-0">Regresar al Inicio: <a type="button" class="btn btn-info btn-sm" href="{% url 'Inicio' %}"><strong>Inicio</strong></a></p>
</div>



{% endif %}


{% endblock %}