carro/urls.py
from django.urls import path
from . import views


app_name="carro"

urlpatterns = [

    path('',views.carrito,name="Carro"),
    path("agregar/<int:producto_id>/",views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/",views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/",views.restar_producto, name="restar"),
    path("limpiar/",views.limpiar_carro, name="limpiar"),
    path("actualizar/<int:producto_id>/<int:cantidad>/",views.actualizar_carro, name="actualizar"),


]

peluqueriamim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('peluqueriamimapp.urls')),

    path('productos/', include('producto.urls')),

    path('contacto/', include('contacto.urls')),

    path('autenticacion/', include('autenticacion.urls')),

    path('pedidos/', include('pedidos.urls')),

    path('carro/', include('carro.urls')),



]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

producto/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('',views.productos,name="Productos"),

]

carro/models.py
from django.db import models

# Create your models here.

producto/models.py
from django.db import models

# Create your models here.


class CategoriaProd(models.Model):
    nombre=models.CharField(max_length=60)
    created=models.DateField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name='categoriaProd'
        verbose_name_plural='categoriasProd'

    def __str__(self):
        return self.nombre



class Producto(models.Model):
    nombre=models.CharField(max_length=60)
    precio=models.FloatField()
    categorias=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    stock=models.IntegerField()
    imagen=models.ImageField(upload_to='productos')
    descripcion=models.CharField(max_length=400)
    created=models.DateField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name='producto'
        verbose_name_plural='productos'

    def __str__(self):
        return self.nombre
            

"""
class Producto(models.Model):
    nombre=models.CharField(max_length=60)
    categorias=models.ForeignKey(CategoriaProd, )
    precio=models.FloatField()
    stock=models.IntegerField()
    imagen=models.ImageField(upload_to='productos')

    class Meta:
        verbose_name='producto'
        verbose_name_plural='productos'

        def __str__(self):
            return self.titulo


"""

carro/views.py
from django.shortcuts import render, redirect

from .carro import Carro

from producto.models import Producto


# Create your views here.


def carrito(request):
    return render(request, "carro/carrito.html")

def agregar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.agregar(producto=producto)

    return redirect("Productos")


def eliminar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.eliminar(producto=producto)

    return redirect("Productos")

def restar_producto(request, producto_id):

    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.restar_producto(producto=producto)

    return redirect("Productos")

def limpiar_carro(request):

    carro=Carro(request)

    carro.limpiar_carro()

    return redirect("Productos")

def actualizar_carro(request, producto_id, cantidad):
    carro=Carro(request)

    producto=Producto.objects.get(id=producto_id)

    carro.actualizar_carro(producto=producto, cantidad=cantidad)

    return redirect("carro:Carro")

    

producto/views.py
from django.shortcuts import render
from producto.models import Producto
# Create your views here.


def productos(request):
    productos=Producto.objects.all()
    return render(request, "productos/productos.html", {"productos": productos})

producto/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>
        <tr>
            <th colspan="3" class="text-center">carro de compras</th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Precio</th>
        </tr>


    </thead>
    <tbody>
        
        {% if request.user.is_authenticated %}
        {%if request.session.carro.items %}
            {%for key, value in request.session.carro.items%}
                <tr class="tex-center">
                    <td>{{value.nombre}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a><br/>

                        $ {{value.precio}}
                    </td>
                    
                </tr>

            {% endfor %}

        {% else %}
            <tr>
                <td colspan="3"><div class="alert alert-danger text-center"> No hay productos en el carro</div></td>
            </tr>
        {% endif %}
        {% else %}

            <tr>
                <td colspan="3"><div class="alert alert-danger text-center"> Tienes que iniciar sesion</div></td>
            </tr>

        {% endif %}

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">  <p style="color: white;">Total: $ {{importe_total_carro}}</p></td>
        </tr>

    </tfoot>




</table>