carro/urls.py
from django.urls import path
from . import views


app_name="carro"

urlpatterns = [

    path('',views.carrito,name="Carro"),
    path("agregar/<int:producto_id>/",views.agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/",views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/",views.restar_producto, name="restar"),
    path("limpiar/",views.limpiar_carro, name="limpiar"),
    path("actualizar/<int:producto_id>/<int:cantidad>/",views.actualizar_carro, name="actualizar"),


]

peluqueriamim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('peluqueriamimapp.urls')),

    path('productos/', include('producto.urls')),

    path('contacto/', include('contacto.urls')),

    path('autenticacion/', include('autenticacion.urls')),

    path('pedidos/', include('pedidos.urls')),

    path('carro/', include('carro.urls')),



]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peluqueriamimapp/urls.py
from django.urls import path
from peluqueriamimapp import views

urlpatterns = [

    path('',views.home,name="Inicio"),
    

]

peluqueriamimapp/views.py
from django.shortcuts import render
from carro.carro import Carro
# Create your views here.

def home(request):
    carro=Carro(request)
    
    return render(request, "peluqueriamimapp/home.html")

peluqueriamimapp/templates/peluqueriamimapp/backupbase.html
<html>

<head>

    {% load static %}
   
    <!-- Bootstrap -->
    <link href="{% static 'peluqueriamimapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'peluqueriamimapp/css/gestion.css'%}" rel="stylesheet">
</head>

<body>

   <!--  <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Peluqueria y Estetica MYM</span>
      </h1>
    -->

 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <label for="" class="brand">
        <a href="{% url 'Inicio' %}" class="logo"><img src="{% static 'peluqueriamimapp/img/logomain.png' %}" alt="" ><h3 class="nombre-empresa">Peluqueria y Estetica MYM</h3></a>
      </label>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'Inicio' %}">Productos Esteticos</a>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Inicio' %}"><h5>Inicio</h5></a>
          </li>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Productos' %}"><h5>Productos</h5></a>
          </li>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Contacto' %}"><h5>Contacto</h5></a>
          </li>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Productos' %}"><h5>Carrito de compras</h5></a>
          </li>
          </ul>
      </div>
    </div>
  </nav>

  <!-- Contenido Variable-->
  {% block content %}

  {% endblock %}


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Productos Esteticos 2022</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'peluqueriamimapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'peluqueriamimapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

peluqueriamimapp/templates/peluqueriamimapp/base.html
<html>

<head>

    {% load static %}
   
    <!-- Bootstrap -->
    <link href="{% static 'peluqueriamimapp/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'peluqueriamimapp/css/gestion.css'%}" rel="stylesheet">
</head>

<body>

   <!--  <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Peluqueria y Estetica MYM</span>
      </h1>
    -->

 <!-- Navbar -->

 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'Inicio' %}"><h4>Inicio</h4></a>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'Productos' %}"><h4>Productos</h4></a>
          </li>
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'Contacto' %}"><h4>Contactanos</h4></a>
          </li>
          </ul>
        </div>
      </div>
  </nav>

<!-- Navbar Logo -->

  <nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
  <div class="container">
    <label for="" class="brand">
      <a href="{% url 'Inicio' %}" class="logo"><img src="{% static 'peluqueriamimapp/img/logomain.png' %}" alt="" ><h3 class="nombre-empresa nav-item" >Peluqueria y Estetica MYM</h3></a>
    </label>
    <div style="float: right;">
      <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <h5>Hola {{ user.username }}</h5></a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'cerrar_sesion' %}">Cerrar Sesion</a>
                </div>
            </li>
            {%else%}
            <li class="nav-item">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'logear' %}"><h5> Login/Registro </h5></a>
            </li>
            {% endif %}
        <li class="nav-item">
          <a class="nav-link text-uppercase text-expanded" href="{% url 'carro:Carro' %}"><h5>Carrito de compras</h5></a>
        </li>
        </ul>
    </div>
  </div>
</nav>

  <!-- Contenido Variable-->
  {% block content %}

  {% endblock %}


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        <p class="m-0 mbt">
        	<a href="sample.html" class="link">Política de privacidad</a> ·
        	<a href="sample.html" class="link">Aviso legal</a> ·
        	<a href="sample.html" class="link">Cookies</a>
		</p>
        <p class="m-0 mbt1">&copy; Productos Esteticos 2022</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'peluqueriamimapp/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'peluqueriamimapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

peluqueriamimapp/templates/peluqueriamimapp/home.html
{% extends "peluqueriamimapp/base.html" %}

{% load static %}
{% block content %}

   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'peluqueriamimapp/img/Productosimg.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Puntualidad</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con el envío express.
          </p>
         
        </div>
      </div>
    </div>
  </section>


  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Nos comprometemos en cumplir con las expectativas del cliente y si el prodcuto no llega en buenas condiciones te daremos un reembolso.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}